server:
  servlet:
    context-path: /exam
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://host.docker.internal:3306/exam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
minIO:
  url: host.docker.internal
  #url: 127.0.0.1
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  imgBucket: exam-img
